# Generated by Django 4.2.16 on 2025-01-26 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('permanent_address', models.CharField(max_length=150)),
                ('current_address', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_no', models.BigIntegerField()),
                ('other_phone', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=50)),
                ('fee_per_sem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exam_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('no_of_year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseSubject',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_code', models.CharField(max_length=10)),
                ('subject_name', models.CharField(max_length=50)),
                ('credit_hours', models.PositiveIntegerField()),
                ('full_marks', models.PositiveIntegerField()),
                ('pass_marks', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='administration.course')),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('deg_id', models.AutoField(primary_key=True, serialize=False)),
                ('sym', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('ex_id', models.AutoField(primary_key=True, serialize=False)),
                ('sym', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('salary_id', models.AutoField(primary_key=True, serialize=False)),
                ('salary_position', models.CharField(max_length=100)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medical_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hr_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('sem_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='administration.course')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30)),
                ('applicant_status', models.IntegerField(choices=[(1, 'Permanent'), (2, 'Part Time')])),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10)),
                ('higher_edu_cmp', models.DateField()),
                ('graduation_certificate', models.ImageField(blank=True, null=True, upload_to='teacher_certificate/')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='teacher_profile_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.address')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.contactinfo')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.degree')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.salary')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSalaryReport',
            fields=[
                ('salary_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now=True)),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.salary')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_reports', to='administration.teacherinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherCourses',
            fields=[
                ('tc_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.ManyToManyField(to='administration.coursesubject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='administration.teacherinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='administration.teacherinfo')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30)),
                ('father_name', models.CharField(max_length=30)),
                ('roll_no', models.CharField(blank=True, max_length=20, null=True)),
                ('discount', models.BooleanField(choices=[(True, 'Applied'), (False, 'Not Applied')], default=False)),
                ('dsc_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('applicant_status', models.BooleanField(choices=[(True, 'Addmited'), (False, 'Not Addmited')], default=False)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10)),
                ('ten_completion_date', models.DateField()),
                ('ten_passed_certificate', models.ImageField(blank=True, null=True, upload_to='student_certificate/')),
                ('twelve_completion_date', models.DateField()),
                ('twelve_passed_certificate', models.ImageField(blank=True, null=True, upload_to='student_certificate/')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='student_profile_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.address')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.contactinfo')),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='administration.semester')),
                ('ten_examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_ten_exam', to='administration.examination')),
                ('twelve_examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_twelve_exam', to='administration.examination')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('fee_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_num', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_date', models.DateTimeField(auto_now=True)),
                ('semester_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='administration.studentinfo')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_fees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateTimeField(auto_now_add=True)),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='administration.studentinfo')),
            ],
        ),
        migrations.AddField(
            model_name='coursesubject',
            name='sem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='administration.semester'),
        ),
    ]
